#!/bin/bash

echo "adsbxfeed postinst"

UUID_FILE="/etc/AryaOS/UUID.txt"

if [ ! -f $UUID_FILE ]; then
  mkdir -p /etc/AryaOS
  echo "$UUID_FILE doesn't exist, initializing."
  uuidgen > $UUID_FILE
fi

systemctl enable adsbxfeed
systemctl start adsbxfeed

exit 0